server:
#  服务端口
  port: 8764

eureka:
  client:
    service-url:
#      注册到注册中心
      defaultZone: http://localhost:8888/eureka
spring:
  application:
#    注册到注册中心的名字
    name: consumer-service
#    负载均衡策略
  NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule