server:
  port: 6666
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka
spring:
  application:
    name: turbine-service
turbine:
  combine-host-port: true
  app-config: newpro-service,produce-service
#  cluster-name-expression: new String("default")
  instanceUrlSuffix: /hystrix.stream
